"""Generate YouTube guest cookies using a real browser via Playwright,
then export to Netscape cookies.txt format for yt-dlp."""
import asyncio
from pathlib import Path
from playwright.async_api import async_playwright

DATA_DIR = Path(__file__).parent
COOKIES_PATH = DATA_DIR / "cookies.txt"


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()

        print("Navigating to YouTube to generate guest session cookies...")
        await page.goto("https://www.youtube.com", wait_until="networkidle")
        await page.wait_for_timeout(3000)

        # Also visit a video page to get additional cookies
        await page.goto(
            "https://www.youtube.com/watch?v=V3oYVFAx_6w", wait_until="networkidle"
        )
        await page.wait_for_timeout(2000)

        cookies = await context.cookies()
        print(f"Got {len(cookies)} cookies")

        with open(COOKIES_PATH, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by export_cookies.py via Playwright\n\n")
            for c in cookies:
                domain = c["domain"]
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path = c["path"]
                secure = "TRUE" if c.get("secure") else "FALSE"
                expires = int(c.get("expires", 0))
                name = c["name"]
                value = c["value"]
                http_only = c.get("httpOnly", False)
                prefix = "#HttpOnly_" if http_only else ""
                f.write(
                    f"{prefix}{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                )

        await browser.close()
        print(f"Saved {COOKIES_PATH}")


if __name__ == "__main__":
    asyncio.run(main())
